spring.application.name=demo

# \u6587\u5B57\u30B3\u30FC\u30C9\u8A2D\u5B9A
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8
spring.web.encoding.charset=UTF-8
spring.web.encoding.force=true

# JPA\u8A2D\u5B9A\uFF08DB\u306A\u3057\u8D77\u52D5\u7528\uFF09
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Render\u7528\u30DD\u30FC\u30C8\u8A2D\u5B9A
server.address=0.0.0.0
server.port=${PORT:8080}