spring.application.name=demo

# \u6587\u5B57\u30B3\u30FC\u30C9\u8A2D\u5B9A
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.thymeleaf.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8


# =========================
# PostgreSQL(Render)
# =========================
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================
# Render
# =========================
server.address=0.0.0.0
server.port=${PORT:8080}