spring.application.name=demo


# \u6587\u5B57\u30B3\u30FC\u30C9
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.thymeleaf.encoding=UTF-8
server.tomcat.uri-encoding=UTF-8


# PostgreSQL(Render)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Render\u7528
server.address=0.0.0.0
server.port=${PORT:8080}